//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill
    {
        public Nullable<int> InPatientID { get; set; }
        public string PatientName { get; set; }
        public string Sex { get; set; }
        public Nullable<int> Age { get; set; }
        public int Sl_NO_ { get; set; }
        public System.DateTime Date { get; set; }
        public string Discription { get; set; }
        public decimal Amount { get; set; }
        public string Remarks { get; set; }
    
        public virtual InPatient InPatient { get; set; }
    }
}
